### PR TITLE
Benchmark intel xpu

### PR DESCRIPTION
**Pull request by sunjiweiswift**
Added llama for Intel support. The command is still sh benchmark.sh

### CODE REVIEW

**Comment by jerryzh168** [comment]
can you add some test command in summary to show how to run benchmarks for xpu

**Comment by sunjiweiswift** [comment]
> can you add some test command in summary to show how to run benchmarks for xpu

I modified the default_device variable ("default_device = 'cuda' if torch.cuda.is_available() else 'xpu' if torch.xpu.is_available() else 'cpu'") so it will be set to cuda on nvdia gpu and xpu on intel gpu. So I still use the “sh benchmark.sh” command .

**Review by jerryzh168 — APPROVED** [review]

**Comment by sunjiweiswift** [comment]
> @sunjiweiswift are you able to publish some benchmarking results as well? if so please add a new entry similar to https://github.com/pytorch/ao/tree/main/torchao/quantization#uintx-quantization with title "xpu backend"

Currently these quantizations are not fully supported. I updated the benchmark data of bf16 int8dq int8wo, and wikitext-perplexity has not been tested yet, and will be updated in subsequent commits

**Comment by jerryzh168** [comment]
please rebase to resolve conflict before landing

**Comment by sunjiweiswift** [comment]
> please rebase to resolve conflict before landing

The conflict has been resolved. Please complete the merge

**Review by airMeng — APPROVED** [review]

**Comment by airMeng** [comment]
@jerryzh168 could you merge?

**Pull request merged**
