### PR TITLE
Enable Intel GPU

### PR DESCRIPTION
**Pull request by dbyoung18**
This PR is migrated from gpt-fast [#79](https://github.com/pytorch-labs/gpt-fast/pull/79). We would like to add initial support for Intel GPU in torch-ao with the device option "xpu"(i.e., --device "xpu"). Currently, both BF16 & INT8 under eager mode and compile mode are functionally supported. INT4 support and further performance improvement are WIP.

Here are the steps to run Llama2-7b and Llama3-8b generation on Intel GPU with torch-ao. We will update the tutorial later with improved performance.

Launch
1. command for BF16
python generate.py --checkpoint_path checkpoints/$MODEL_REPO/model.pth/model.pth --write_result benchmark_results.txt --device xpu --precision torch.bfloat16
2. command for INT8 dynamic quantization
python generate.py --checkpoint_path checkpoints/$MODEL_REPO/model.pth/model.pth --write_result benchmark_results.txt --device xpu --quantization int8dq
3. command for INT8 weight-only quantization
python generate.py --checkpoint_path checkpoints/$MODEL_REPO/model.pth/model.pth --write_result benchmark_results.txt --device xpu --quantization int8wo

### CODE REVIEW

**Comment by msaroufim** [comment]
Hi @dbyoung18 thank you for this PR, as of today we're trying to get AO working with no extra dependencies outside of torch. This is a bit constraining and we're going to look at supporting alternate backends later this year just not yet

**Comment by msaroufim** [comment]
Thanks for your PR @dbyoung18, my preference here would be to land generic accelerator memory APIs in core and then use those. That way  we wouldn't need to ask people that are trying to use Intel GPUs to change their code so it'd be something like `torch.get_accelerator().max_memory_reserved()` or `torch.accelerator.max_memory_reserved()`

@guangyey

**Comment by guangyey** [comment]
Hi @msaroufim and @dbyoung18 , let me explain the plan.
In the long term, we have a proposal to provide device-agnostic APIs for each accelerator. We would like to start from the runtime device and stream component. And then gradually cover the allocator memory APIs. Our RFC is [[RFC] A device-agnostic Python runtime API design for stream-based accelerators](https://github.com/pytorch/pytorch/issues/128403)
In the short term, for XPU, we plan to provide those memory APIs first in case block the customer usage. We have prepared a series of PRs to implement them. You can refer to [#129919](https://github.com/pytorch/pytorch/pull/129919)  and it will be landed soon if everything goes well.

**Comment by dbyoung18** [comment]
> Hi @msaroufim and @dbyoung18 , let me explain the plan. In the long term, we have a proposal to provide device-agnostic APIs for each accelerator. We would like to start from the runtime device and stream component. And then gradually cover the allocator memory APIs. Our RFC is [[RFC] A device-agnostic Python runtime API design for stream-based accelerators](https://github.com/pytorch/pytorch/issues/128403) In the short term, for XPU, we plan to provide those memory APIs first in case block the customer usage. We have prepared a series of PRs to implement them. You can refer to [#129919](https://github.com/pytorch/pytorch/pull/129919) and it will be landed soon if everything goes well.

Thanks @msaroufim  & @guangyey for the above comments. Also add @jgong5 & @rogerxfeng8 from Intel to the conversion
@msaroufim Is it ok for contribute with the short term plan first? (keeping `torch.xpu.max_memory_reserved()` and `import intel_extension_for_pytorch as ipex` in the script to support torch-ao on Intel XPU currently). Once the functionality is ready in upstream PyTorch, we will remove the xpu specific code with generic interface.
We would like to catch some design & implementation in torch-ao on Intel side, as the xpu backend is also on the way of upstreaming to the current pytorch. @jgong5 & @rogerxfeng8 Welcome to bring some comments on this. THX:)

**Comment by dbyoung18** [comment]
Convert to draft first as the PR is going to some internal reviews first.

**Comment by EikanWang** [comment]
@dbyoung18 , may I know why the change is [torchao/_models/llama/generate.py](https://github.com/pytorch/ao/pull/753/files#diff-608f69e373105b539411379f7c1930589b600fd0f0c89ce5890934eda727b233) only?

**Review by malfet — COMMENTED** [review]
I'll leave it up to repo maintainers, but IMO one need to think a bit more about unifying device approach rather than migrating long strings of `elif`s from repo to repo

**Comment by msaroufim** [comment]
I'm already planning on writing an RFC on how we'll support more hardware architectures. RIght now ao is very much NVIDIA device centric but a lot of recent issues have been about supporting more hardware architectures on more operating systems. We need to think about generalizing devices, CI/testing and performance carefully.

**Comment by EikanWang** [comment]
We are working on device-agnostic runtime API for accelerators. It may help `ao` to support more hardware architectures.

@malfet , @msaroufim FYI - https://dev-discuss.pytorch.org/t/python-c-api-rules-for-device-generic-apis/2511

**Comment by msaroufim** [comment]
@EikanWang are there are any github runners for Intel GPUs to ensure our test suite works? We don't have to run the code per commit but at least a nightly check to make sure we understand what works and what doesnt would be helpful

**Comment by EikanWang** [comment]
@msaroufim , may I know if two runners for Intel GPUs are good enough now for the ao nightly?

**Comment by msaroufim** [comment]
> @msaroufim , may I know if two runners for Intel GPUs are good enough now for the ao nightly?

Yup that should be fine! We won't be running on Intel runners per commit for now. cc @atalman @seemethere as well

**Comment by EikanWang** [comment]
Sounds good! We will add two runners to Intel GPU CI/CD resource pool and reserve the two runners dedicated to ao nightly.

cc @riverliuintel, @chuanqi129

**Comment by chuanqi129** [comment]
> Sounds good! We will add two runners to Intel GPU CI/CD resource pool and reserve the two runners dedicated to ao nightly.
> 
> cc @riverliuintel, @chuanqi129

Currently, we have 16 **pytorch organization level** xpu runners with label `"linux.idc.xpu"` used for pytorch CICD. I think the torchao repo can use them directly.

**Comment by EikanWang** [comment]
@chuanqi129 , @riverliuintel, any update?

**Comment by msaroufim** [comment]
They'd need to be hooked up to the Nova workflows as well, see #999 which ran into some issues as well

**Comment by msaroufim** [comment]
@EikanWang we leverage some reusuable github workflows https://github.com/pytorch/ao/blob/main/.github/workflows/regression_test.yml#L68 produced by `pytorch/test-infra` this lets us easily build and test ao on multiple architectures and devices 

We could potentially do a 1 off run of our test suite to see what works in ao out of the box today but will be hard to track progress without the CI integration. 

As to how to integrate with Nova workflows your best bet is to reach out to @seemethere and @atalman on the Intel slack channel. Feel free to tag me there as well so we can move faster

**Comment by mingfeima** [comment]
@dbyoung18 does this one support int4 woq ?

**Comment by dbyoung18** [comment]
> @dbyoung18 does this one support int4 woq ?

Currently, it doesn't support int4 woq on Intel GPU. We are in the upstream progress to support INT4 xpu backend in PyTorch(targetting v2.5). Once the upstream is ready,  will continue adding support on ao side.

**Comment by dbyoung18** [comment]
Closed due to duplicate w/ PR:[ao#1259](https://github.com/pytorch/ao/pull/1259). THX for above review comments.

**Pull request closed without merging**
