### PR TITLE
Move quantization/prototype -> prototype/quantization

### PR DESCRIPTION
**Pull request by jainapurva**
Issue : https://github.com/pytorch/ao/issues/1013

### CODE REVIEW

**Comment by jerryzh168** [comment]
thanks, this will be bc-breaking for QAT I think, will be good to import the diff and fix the torchtune stuff before landing I feel

**Comment by vkuzo** [comment]
> thanks, this will be bc-breaking for QAT I think, will be good to import the diff and fix the torchtune stuff before landing I feel

If some of this code has internal callsites, should it move out of prototype?  Prototype shouldn't have any BC guarantees. cc @andrewor14

**Comment by andrewor14** [comment]
Yeah sounds good, I will submit a separate PR to move QAT out of prototype and update all internal imports. @jainapurva for now can you leave the qat/ directory in its original place so you don't run into conflicts later? You can move the rest

**Comment by andrewor14** [comment]
https://github.com/pytorch/ao/pull/1091

**Pull request closed without merging**
