### PR TITLE
Update base.h unit to unsigned int

### PR DESCRIPTION
**Pull request by EnragedAntelope**
Changed uint to unsigned int to address error when building from source.

### CODE REVIEW

**Review by jcaip — APPROVED** [review]
Thanks for the fix! Should be fine to mere once tests pass

**Comment by msaroufim** [comment]
Hi @EnragedAntelope thank you for the contribution - some next steps
1. Can you merge or rebase to main to avoid the regression test failure
2. Can you please sign the CLA agreement otherwise we won't be able to merge this
3. Can you make it clearer what kind of device, operating system, gpu etc.. you're running such that you're getting from source installation errors?

**Comment by matthewdouglas** [comment]
@msaroufim See #951, likely Windows/MSVC. Very similar issue to the changes made in FP6 which used some non-standard types like 'u_int8_t`.

**Comment by EnragedAntelope** [comment]
> Hi @EnragedAntelope thank you for the contribution - some next steps
> 
>     1. Can you merge or rebase to main to avoid the regression test failure
> 
>     2. Can you please sign the CLA agreement otherwise we won't be able to merge this
> 
>     3. Can you make it clearer what kind of device, operating system, gpu etc.. you're running such that you're getting from source installation errors?

Hi,
Happy to help but sorry I won't sign that agreement, it requires actual name etc. I haven't been asked that for open source github before. 

If there's a way to proceed without that I'm happy to try again with latest base. 

For 3, I am running Windows 11 on a PC with 4090 GPU. Python 3.11.9.

**Comment by msaroufim** [comment]
@EnragedAntelope you can read more about CLAs here https://github.com/github/github-ospo/blob/main/policies/contributor-license-agreements.md but the intent is to say you give us the permission to use your contribution. It's quite common for projects managed by larger companies. Unfortunately I wouldn't even be able to copy paste your contribution since it's yours

**Comment by EnragedAntelope** [comment]
Thanks for the additional info. I signed the agreement and updated my fork. Should be good to go.

**Review by msaroufim — APPROVED** [review]

**Pull request merged**
