### PR TITLE
Add new evaluation metrics

### PR DESCRIPTION
**Pull request by jainapurva**
Added new tests to llama/eval.sh for more extensive testing on larger metrics

### CODE REVIEW

**Comment by jerryzh168** [comment]
if not sure if all eval metrics are relevant for llama, cc @HDCharles to take a look

**Review by HDCharles — CHANGES_REQUESTED** [review]
see comment

**Comment by jainapurva** [comment]
> the current solution is specifying all tests explicitly in benchmarks.sh and we made evals.sh to do the same though I haven't added all the tests there yet. If you want to make it easier to run those sets i'd maybe add them there?

I think we need more eval metrics to test the different techniques on llama. Though that could be done by updating the eval.sh instead. Also, we can add more benchmarks to the readme file in future.

**Comment by drisspg** [comment]
@HDCharles just to confirm this is what you have in mind right?

**Review by HDCharles — APPROVED** [review]
this looks better

**Pull request merged**
