### PR TITLE
Revert "Pin PT version: Fix FPX Inductor error"

### PR DESCRIPTION
**Pull request by msaroufim**
Reverts pytorch/ao#790

### CODE REVIEW

**Comment by msaroufim** [comment]
Hmm looks like still can't land this, will try again tmrw

**Comment by gau-nernst** [comment]
Should be fixed once https://github.com/pytorch/pytorch/pull/135301 lands in core
Tracking issue in core https://github.com/pytorch/pytorch/issues/135160

**Comment by gau-nernst** [comment]
Just tested with `2.5.0.dev20240908` and the tests pass. @msaroufim You can try to land this again.

**Comment by msaroufim** [comment]
I saw some new errors unfortunately here https://github.com/pytorch/ao/pull/843

**Pull request closed without merging**
