### PR TITLE
Add `quantize` to doc page

### PR DESCRIPTION
**Pull request by jerryzh168**
Summary:
att

Test Plan:
.

Reviewers:

Subscribers:

Tasks:

Tags:

### CODE REVIEW

**Review by msaroufim — APPROVED** [review]

**Comment by msaroufim** [comment]
So I was going over this https://docs-preview.pytorch.org/pytorch/ao/367/generated/torchao.quantization.quantize.ht
Screenshot 2024-06-14 at 3 00 10 PM
ml#torchao.quantization.quantize

The docstrings aren't particularly clear, the main omissions are
1. Not showing the various algorithms users can pass in a string or callable
2. weight settings take up too much real estate when some reasonable defaults might be better
3. you mention subclasses but i'd suspect most users would have no idea what that is
4. There isn't an example of a filter_fn

**Comment by jerryzh168** [comment]
updated, but I'm not sure how to resolve 3

**Comment by msaroufim** [comment]
I'm guessing we can wait on merging this until the UX issues are finalized

**Comment by jerryzh168** [comment]
@msaroufim updated, please take a look again

**Review by msaroufim — APPROVED** [review]

**Pull request merged**
