### PR TITLE
Revert "Pin PT version: Fix FPX Inductor error"

### PR DESCRIPTION
**Pull request by msaroufim**
Reverts pytorch/ao#790

The problems are all mostly cpu specific, in particular this feels like a subclass on cpu problem but not sure - cc @bdhirsh

### CODE REVIEW

**Comment by msaroufim** [comment]
so fpx test is no longer failing but i see some new failures with bitnet that should probably be skipped @andrewor14 before we make the release. Also save/load is now failing on nightlies @jerryzh168

**Review by andrewor14 — APPROVED** [review]

**Comment by bdhirsh** [comment]
@msaroufim do you have a link to the failing tests? I can try to help root cause (and/or at least figure out if it's subclass related)

**Comment by bdhirsh** [comment]
A couple things:

(1) I confirmed that `python test/integration/test_integration.py -k test_int8_weight_only_quant_subclass_api_1_cpu` fails for me locally

(2) I tweaked the test to compile with a few different backends: `compile(... backend="inductor")` fails, but `compile(..., backend="aot_eager_decomp_partition")` runs fine

(3) i checked out @eellison's beautiful inductor bisecting tool from [here](https://github.com/pytorch/pytorch/pull/131936) and ran it. It bisected down to to the lowering for `prims.convert_element_type` as the "problematic" bit of inductor. This is technically useful, but doesn't really give us the full story: that lowering hasn't been changed in months, and avoiding lowering that op probably just prevents inductor from doing some other fusions that are causing the numeric difference (I bet if the bisector could bisect on inductor fusions it could tell us more).

(4) Also confirmed that this only repros with cpu inputs.

Idk, @eellison do you know any suspicious commits coming from the cpu-inductor side in the last week that could affect numerics, especially in relation to casting ops?

**Comment by leslie-fang-intel** [comment]
Hi @bdhirsh

> (1) I confirmed that python test/integration/test_integration.py -k test_int8_weight_only_quant_subclass_api_1_cpu fails for me locally

is it the same failure reported in https://github.com/pytorch/pytorch/issues/135830

**Comment by eellison** [comment]
@bdhirsh, I was on pto last week so i'm not sure. sounds like @leslie-fang-intel has an idea.

**Comment by bdhirsh** [comment]
@leslie-fang-intel not sure, but seems unlikely (mainly because the issue you linked is a hard error while the subclass is running at compile time, while this is a runtime / bad numerics error)

**Comment by leslie-fang-intel** [comment]
Thanks @bdhirsh. It sounds like a different error then. Maybe after we resolve the first one, we will meet the numeric error you met. Do you have any idea about the hard error in https://github.com/pytorch/pytorch/issues/135830? Why it didn't happen in your test environment.

**Comment by leslie-fang-intel** [comment]
Hi @bdhirsh, I have create PRs to fix these 2 failures

- PR in Torch: https://github.com/pytorch/pytorch/pull/135928 addresses the numerical failures, which were caused by missing the fusion of this woq int8 pattern and falling back to the reference implementation. By re-enabling the fusions in Inductor for this pattern, the unit tests now pass on my local system.
- PR in AO: https://github.com/pytorch/ao/pull/884, as for another UT failure `python test/integration/test_integration.py -k test_int8_weight_only_quant_with_freeze`, it seems we still need `unwrap_tensor_subclass` for Inductor `freezing`. cc @eellison here.

Please kindly help to review these 2 PRs.

**Comment by bdhirsh** [comment]
@jerryzh168 I vaguely remember it being a problem to re-enable `unwrap_tensor_subclass()` in the torch.compile path for torchao, since dynamo had a bad interaction with the parametrization code. Does that ring a bell?

Either way, we should fix the freezing interaction (@IvanKobzarev is taking a look)

**Pull request merged**
