### PR TITLE
Clean up FP6-LLM

### PR DESCRIPTION
**Pull request by gau-nernst**
- Remove original FP6 quantization code (qtorch and C++ bit-packing)
- Replace FP32<->FP6 dtype conversion with @vkuzo's implementation for MX dtypes
  - I also migrate some of my FP32->FP6 rounding test cases to MX custom cast test.

### CODE REVIEW

**Comment by vkuzo** [comment]
> Replace FP32<->FP6 dtype conversion with @vkuzo's implementation for MX dtypes

I have two questions:
1. Just curious, have you benchmarked the performance of this change?  I have not optimized the mx types for performance yet.
2. I think it's not ideal to depend on code in `prototype` folder, if other people need `custom_cast.py` it might be good to move it to a common place outside of the `prototype` folder.

**Comment by gau-nernst** [comment]
@vkuzo 
1. I did benchmarking. IIRC, your implementation is faster than mine for both CPU and GPU (w/ torch.compile). Will benchmark it again and update the result in this comment. (I also did correctness comparison. Your implementation and mine are bit-identical for all FP16 bit patterns - can't test all FP32 bit patterns because it would take too long)
2. Yea I want to discuss with you about this also. It will be good to move it to a separate file for low bit-width floating point conversion. The FP6-LLM author added support for FP5 E2M2, so I want to support FP5 also (mx doesn't have FP5).

A question for @msaroufim. Is there a guideline when we should or should not decorate a function with `@torch.compile`? These functions rely on torch.compile to be fast, but there are cold-start (first time is slow) and dynamic shape (can we avoid re-compile on different shapes, in a guaranteed way?) problems. (haven't looked into the problems too much yet, maybe it is not that significant).

**Comment by msaroufim** [comment]
So for Windows the main issue is `torch.compile()` codegenerates triton kernels which hasn't prioritized Windows support. I think for inductor cpu backend this should be less of an issue, I suspect there might be an overly aggressive assert somewhere though.

I would say overall everything should be compilable, the cold start problems is indeed annoying and is actively being worked, there are some broader plans that have been shared though https://dev-discuss.pytorch.org/t/how-to-bring-compile-time-down-to-zero-our-plans-and-direction-may-14th-edition/2089

Regarding dynamic shapes the way I iterate through things is first eliminate graph breaks then recompilations, this has been my goto guide https://github.com/pytorch/pytorch/blob/main/docs/source/torch.compiler_troubleshooting.rst

Also just FYI we removed the requirement to have branches up to date before merge, there was a breaking change in PyTorch that was just reverted so please rebase your changes to get rid of CI flakes

**Review by msaroufim — APPROVED** [review]
that's a lot of deletions 🗡️

**Pull request merged**
