### PR TITLE
Add support for Llama 3.2. 3B in eval/bench pipelines

### PR DESCRIPTION
**Pull request by Diogo-V**
## Description:
* This PR adds support for running Llama 3.2. 3b in the evaluation and benchmark pipelines

## Notes
* Even though 3B is not the most vRAM taxing of models, it can be useful for people with lower end GPUs (such as me) to iterate and validate parts of the codebase
* Sources:
  * https://github.com/huggingface/transformers/blob/main/src/transformers/modeling_utils.py#L2929
  * https://github.com/huggingface/candle/pull/2508/commits/3837d4bbc9ecd6a3bad1274c738984ebac03fc54

Let me know if there is anything that is missing or that I should refactor!

### CODE REVIEW

**Comment by msaroufim** [comment]
can you the logs of a sample run locally? unfortunately I don't believe we run this model in CI

Granted I'd love it if we could start running some benchmarks in our github actions and store the results in github artifacts, we recently even got access to an H100 - cc @HDCharles

**Comment by Diogo-V** [comment]
Absolutely! I’ll post it later today.

Do you think it would be useful to add this to the CI pipeline?

This PR came up while I was working on #1174. I currently do not have access to bigger GPU instances and I had to switch to a smaller model for testing. I figured others might be in similar constraints, so I decided to open this PR to make the smaller model option available if people want to run the eval.py or generate.py scripts locally

**Comment by msaroufim** [comment]
> Absolutely! I’ll post it later today.
> 
> Do you think it would be useful to add this to the CI pipeline?
> 
> This PR came up while I was working on #1174. I currently do not have access to bigger GPU instances and I had to switch to a smaller model for testing. I figured others might be in similar constraints, so I decided to open this PR to make the smaller model option available if people want to run the eval.py or generate.py scripts locally

It is extremely useful yes but might be best as a nightly job - idea would be the job runs nightly, downloads model weights, makes a few inferences, store result to disk, store disk results in a github artifact

ChatGPT is pretty good at writing CI jobs so if you wanna take a stab at it, I'd be happy to help you merge the code

**Comment by jerryzh168** [comment]
nit: can you include 3.2 in https://github.com/pytorch/ao/blob/main/scripts/prepare.sh as well

**Comment by Diogo-V** [comment]
> can you show the logs of a sample run locally? unfortunately I don't believe we run this model in CI
> 
> Granted I'd love it if we could start running some benchmarks in our github actions and store the results in github artifacts, we recently even got access to an H100 - cc @HDCharles

Running a sample eval.sh script with llama 3b and limit=2 as follows:
```sh
export CHECKPOINT_PATH=../../../checkpoints # path to checkpoints folder

export MODEL_REPO=meta-llama/Llama-3.2-3B
python eval.py --checkpoint_path $CHECKPOINT_PATH/$MODEL_REPO/model.pth
python eval.py --checkpoint_path $CHECKPOINT_PATH/$MODEL_REPO/model.pth --quantization int8wo
python eval.py --checkpoint_path $CHECKPOINT_PATH/$MODEL_REPO/model.pth --quantization int4wo-64
python eval.py --checkpoint_path $CHECKPOINT_PATH/$MODEL_REPO/model.pth --quantization float8wo
python eval.py --checkpoint_path $CHECKPOINT_PATH/$MODEL_REPO/model.pth --quantization float8dq-tensor
```

Got the below logs:
<details>
<summary>Logs</summary>
Evaluating model ../../../checkpoints/meta-llama/Llama-3.2-3B/model.pth on tasks: ['wikitext'], limit: 2, device: cuda, precision: torch.bfloat16, quantization: None, compile: False, max_length: None, calibration_tasks: ['wikitext'], calibration_seq_length: 100, pad_calibration_inputs: False

Loading model ...
Time to load model: 0.12 seconds
Running evaluation ...
2024-11-14:01:12:21,209 INFO     [huggingface.py:129] Using device 'cpu'
2024-11-14:01:12:26,830 INFO     [huggingface.py:481] Using model type 'default'
2024-11-14:01:12:27,062 INFO     [huggingface.py:365] Model parallel was set to False, max memory was not set, and device map was set to {'': 'cpu'}
2024-11-14:01:12:29,343 INFO     [__init__.py:459] The tag 'arc_ca' is already registered as a group, this tag will not be registered. This may affect tasks you want to call.
2024-11-14:01:12:29,356 INFO     [__init__.py:459] The tag 'arc_ca' is already registered as a group, this tag will not be registered. This may affect tasks you want to call.
2024-11-14:01:12:31,321 WARNING  [task.py:799] [Task: wikitext] metric word_perplexity is defined, but aggregation is not. using default aggregation=weighted_perplexity
2024-11-14:01:12:31,321 WARNING  [task.py:811] [Task: wikitext] metric word_perplexity is defined, but higher_is_better is not. using default higher_is_better=False
2024-11-14:01:12:31,321 WARNING  [task.py:799] [Task: wikitext] metric byte_perplexity is defined, but aggregation is not. using default aggregation=weighted_perplexity
2024-11-14:01:12:31,321 WARNING  [task.py:811] [Task: wikitext] metric byte_perplexity is defined, but higher_is_better is not. using default higher_is_better=False
2024-11-14:01:12:31,321 WARNING  [task.py:799] [Task: wikitext] metric bits_per_byte is defined, but aggregation is not. using default aggregation=bits_per_byte
2024-11-14:01:12:31,321 WARNING  [task.py:811] [Task: wikitext] metric bits_per_byte is defined, but higher_is_better is not. using default higher_is_better=False
Repo card metadata block was not found. Setting CardData to empty.
2024-11-14:01:13:00,888 WARNING  [repocard.py:108] Repo card metadata block was not found. Setting CardData to empty.
Evaluating Model On:  {'wikitext': ConfigurableTask(task_name=wikitext,output_type=loglikelihood_rolling,num_fewshot=None,num_samples=62)}
2024-11-14:01:13:00,914 INFO     [task.py:415] Building contexts for wikitext on rank 0...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 1368.67it/s]
2024-11-14:01:13:00,916 INFO     [evaluator.py:489] Running loglikelihood_rolling requests
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.01s/it]
wikitext: {'alias': 'wikitext', 'word_perplexity,none': 11.72036418687775, 'word_perplexity_stderr,none': 'N/A', 'byte_perplexity,none': 1.6099144124991513, 'byte_perplexity_stderr,none': 'N/A', 'bits_per_byte,none': 0.6869839927217813, 'bits_per_byte_stderr,none': 'N/A'}

Evaluating model ../../../checkpoints/meta-llama/Llama-3.2-3B/model.pth on tasks: ['wikitext'], limit: 2, device: cuda, precision: torch.bfloat16, quantization: int8wo, compile: False, max_length: None, calibration_tasks: ['wikitext'], calibration_seq_length: 100, pad_calibration_inputs: False

Loading model ...
Time to load model: 0.11 seconds
Running evaluation ...
2024-11-14:01:13:08,888 INFO     [huggingface.py:129] Using device 'cpu'
2024-11-14:01:13:13,992 INFO     [huggingface.py:481] Using model type 'default'
2024-11-14:01:13:14,254 INFO     [huggingface.py:365] Model parallel was set to False, max memory was not set, and device map was set to {'': 'cpu'}
2024-11-14:01:13:16,672 INFO     [__init__.py:459] The tag 'arc_ca' is already registered as a group, this tag will not be registered. This may affect tasks you want to call.
2024-11-14:01:13:16,685 INFO     [__init__.py:459] The tag 'arc_ca' is already registered as a group, this tag will not be registered. This may affect tasks you want to call.
2024-11-14:01:13:18,634 WARNING  [task.py:799] [Task: wikitext] metric word_perplexity is defined, but aggregation is not. using default aggregation=weighted_perplexity
2024-11-14:01:13:18,634 WARNING  [task.py:811] [Task: wikitext] metric word_perplexity is defined, but higher_is_better is not. using default higher_is_better=False
2024-11-14:01:13:18,634 WARNING  [task.py:799] [Task: wikitext] metric byte_perplexity is defined, but aggregation is not. using default aggregation=weighted_perplexity
2024-11-14:01:13:18,634 WARNING  [task.py:811] [Task: wikitext] metric byte_perplexity is defined, but higher_is_better is not. using default higher_is_better=False
2024-11-14:01:13:18,634 WARNING  [task.py:799] [Task: wikitext] metric bits_per_byte is defined, but aggregation is not. using default aggregation=bits_per_byte
2024-11-14:01:13:18,634 WARNING  [task.py:811] [Task: wikitext] metric bits_per_byte is defined, but higher_is_better is not. using default higher_is_better=False
Repo card metadata block was not found. Setting CardData to empty.
2024-11-14:01:13:46,668 WARNING  [repocard.py:108] Repo card metadata block was not found. Setting CardData to empty.
Evaluating Model On:  {'wikitext': ConfigurableTask(task_name=wikitext,output_type=loglikelihood_rolling,num_fewshot=None,num_samples=62)}
2024-11-14:01:13:46,694 INFO     [task.py:415] Building contexts for wikitext on rank 0...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 1277.39it/s]
2024-11-14:01:13:46,696 INFO     [evaluator.py:489] Running loglikelihood_rolling requests
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.04s/it]
wikitext: {'alias': 'wikitext', 'word_perplexity,none': 11.72036418687775, 'word_perplexity_stderr,none': 'N/A', 'byte_perplexity,none': 1.6099144124991513, 'byte_perplexity_stderr,none': 'N/A', 'bits_per_byte,none': 0.6869839927217813, 'bits_per_byte_stderr,none': 'N/A'}

Evaluating model ../../../checkpoints/meta-llama/Llama-3.2-3B/model.pth on tasks: ['wikitext'], limit: 2, device: cuda, precision: torch.bfloat16, quantization: int4wo-64, compile: False, max_length: None, calibration_tasks: ['wikitext'], calibration_seq_length: 100, pad_calibration_inputs: False

Loading model ...
Time to load model: 0.11 seconds
Running evaluation ...
2024-11-14:01:13:52,680 INFO     [huggingface.py:129] Using device 'cpu'
2024-11-14:01:14:07,533 INFO     [huggingface.py:481] Using model type 'default'
2024-11-14:01:14:07,742 INFO     [huggingface.py:365] Model parallel was set to False, max memory was not set, and device map was set to {'': 'cpu'}
2024-11-14:01:14:10,107 INFO     [__init__.py:459] The tag 'arc_ca' is already registered as a group, this tag will not be registered. This may affect tasks you want to call.
2024-11-14:01:14:10,119 INFO     [__init__.py:459] The tag 'arc_ca' is already registered as a group, this tag will not be registered. This may affect tasks you want to call.
2024-11-14:01:14:12,036 WARNING  [task.py:799] [Task: wikitext] metric word_perplexity is defined, but aggregation is not. using default aggregation=weighted_perplexity
2024-11-14:01:14:12,036 WARNING  [task.py:811] [Task: wikitext] metric word_perplexity is defined, but higher_is_better is not. using default higher_is_better=False
2024-11-14:01:14:12,036 WARNING  [task.py:799] [Task: wikitext] metric byte_perplexity is defined, but aggregation is not. using default aggregation=weighted_perplexity
2024-11-14:01:14:12,036 WARNING  [task.py:811] [Task: wikitext] metric byte_perplexity is defined, but higher_is_better is not. using default higher_is_better=False
2024-11-14:01:14:12,036 WARNING  [task.py:799] [Task: wikitext] metric bits_per_byte is defined, but aggregation is not. using default aggregation=bits_per_byte
2024-11-14:01:14:12,036 WARNING  [task.py:811] [Task: wikitext] metric bits_per_byte is defined, but higher_is_better is not. using default higher_is_better=False
Repo card metadata block was not found. Setting CardData to empty.
2024-11-14:01:14:21,516 WARNING  [repocard.py:108] Repo card metadata block was not found. Setting CardData to empty.
Evaluating Model On:  {'wikitext': ConfigurableTask(task_name=wikitext,output_type=loglikelihood_rolling,num_fewshot=None,num_samples=62)}
2024-11-14:01:14:21,542 INFO     [task.py:415] Building contexts for wikitext on rank 0...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 1370.46it/s]
2024-11-14:01:14:21,544 INFO     [evaluator.py:489] Running loglikelihood_rolling requests
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:05<00:00,  2.79s/it]
wikitext: {'alias': 'wikitext', 'word_perplexity,none': 13.293417578961147, 'word_perplexity_stderr,none': 'N/A', 'byte_perplexity,none': 1.649622099386414, 'byte_perplexity_stderr,none': 'N/A', 'bits_per_byte,none': 0.7221355652081017, 'bits_per_byte_stderr,none': 'N/A'}

Evaluating model ../../../checkpoints/meta-llama/Llama-3.2-3B/model.pth on tasks: ['wikitext'], limit: 2, device: cuda, precision: torch.bfloat16, quantization: float8wo, compile: False, max_length: None, calibration_tasks: ['wikitext'], calibration_seq_length: 100, pad_calibration_inputs: False

Loading model ...
Time to load model: 0.10 seconds
Running evaluation ...
2024-11-14:01:14:32,271 INFO     [huggingface.py:129] Using device 'cpu'
2024-11-14:01:14:41,442 INFO     [huggingface.py:481] Using model type 'default'
2024-11-14:01:14:41,702 INFO     [huggingface.py:365] Model parallel was set to False, max memory was not set, and device map was set to {'': 'cpu'}
2024-11-14:01:14:44,124 INFO     [__init__.py:459] The tag 'arc_ca' is already registered as a group, this tag will not be registered. This may affect tasks you want to call.
2024-11-14:01:14:44,137 INFO     [__init__.py:459] The tag 'arc_ca' is already registered as a group, this tag will not be registered. This may affect tasks you want to call.
2024-11-14:01:14:46,082 WARNING  [task.py:799] [Task: wikitext] metric word_perplexity is defined, but aggregation is not. using default aggregation=weighted_perplexity
2024-11-14:01:14:46,083 WARNING  [task.py:811] [Task: wikitext] metric word_perplexity is defined, but higher_is_better is not. using default higher_is_better=False
2024-11-14:01:14:46,083 WARNING  [task.py:799] [Task: wikitext] metric byte_perplexity is defined, but aggregation is not. using default aggregation=weighted_perplexity
2024-11-14:01:14:46,083 WARNING  [task.py:811] [Task: wikitext] metric byte_perplexity is defined, but higher_is_better is not. using default higher_is_better=False
2024-11-14:01:14:46,083 WARNING  [task.py:799] [Task: wikitext] metric bits_per_byte is defined, but aggregation is not. using default aggregation=bits_per_byte
2024-11-14:01:14:46,083 WARNING  [task.py:811] [Task: wikitext] metric bits_per_byte is defined, but higher_is_better is not. using default higher_is_better=False
Repo card metadata block was not found. Setting CardData to empty.
2024-11-14:01:15:26,820 WARNING  [repocard.py:108] Repo card metadata block was not found. Setting CardData to empty.
Evaluating Model On:  {'wikitext': ConfigurableTask(task_name=wikitext,output_type=loglikelihood_rolling,num_fewshot=None,num_samples=62)}
2024-11-14:01:15:26,850 INFO     [task.py:415] Building contexts for wikitext on rank 0...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 1373.16it/s]
2024-11-14:01:15:26,852 INFO     [evaluator.py:489] Running loglikelihood_rolling requests
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.05s/it]
wikitext: {'alias': 'wikitext', 'word_perplexity,none': 11.75249676221893, 'word_perplexity_stderr,none': 'N/A', 'byte_perplexity,none': 1.6107673755110918, 'byte_perplexity_stderr,none': 'N/A', 'bits_per_byte,none': 0.6877481573410492, 'bits_per_byte_stderr,none': 'N/A'}

Evaluating model ../../../checkpoints/meta-llama/Llama-3.2-3B/model.pth on tasks: ['wikitext'], limit: 2, device: cuda, precision: torch.bfloat16, quantization: float8dq-tensor, compile: False, max_length: None, calibration_tasks: ['wikitext'], calibration_seq_length: 100, pad_calibration_inputs: False

Loading model ...
Time to load model: 0.10 seconds
Running evaluation ...
2024-11-14:01:15:35,994 INFO     [huggingface.py:129] Using device 'cpu'
2024-11-14:01:15:47,286 INFO     [huggingface.py:481] Using model type 'default'
2024-11-14:01:16:05,317 INFO     [huggingface.py:365] Model parallel was set to False, max memory was not set, and device map was set to {'': 'cpu'}
2024-11-14:01:16:07,698 INFO     [__init__.py:459] The tag 'arc_ca' is already registered as a group, this tag will not be registered. This may affect tasks you want to call.
2024-11-14:01:16:07,711 INFO     [__init__.py:459] The tag 'arc_ca' is already registered as a group, this tag will not be registered. This may affect tasks you want to call.
2024-11-14:01:16:09,717 WARNING  [task.py:799] [Task: wikitext] metric word_perplexity is defined, but aggregation is not. using default aggregation=weighted_perplexity
2024-11-14:01:16:09,717 WARNING  [task.py:811] [Task: wikitext] metric word_perplexity is defined, but higher_is_better is not. using default higher_is_better=False
2024-11-14:01:16:09,717 WARNING  [task.py:799] [Task: wikitext] metric byte_perplexity is defined, but aggregation is not. using default aggregation=weighted_perplexity
2024-11-14:01:16:09,717 WARNING  [task.py:811] [Task: wikitext] metric byte_perplexity is defined, but higher_is_better is not. using default higher_is_better=False
2024-11-14:01:16:09,717 WARNING  [task.py:799] [Task: wikitext] metric bits_per_byte is defined, but aggregation is not. using default aggregation=bits_per_byte
2024-11-14:01:16:09,717 WARNING  [task.py:811] [Task: wikitext] metric bits_per_byte is defined, but higher_is_better is not. using default higher_is_better=False
Repo card metadata block was not found. Setting CardData to empty.
2024-11-14:01:16:11,777 WARNING  [repocard.py:108] Repo card metadata block was not found. Setting CardData to empty.
Evaluating Model On:  {'wikitext': ConfigurableTask(task_name=wikitext,output_type=loglikelihood_rolling,num_fewshot=None,num_samples=62)}
2024-11-14:01:16:11,804 INFO     [task.py:415] Building contexts for wikitext on rank 0...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 1359.58it/s]
2024-11-14:01:16:11,806 INFO     [evaluator.py:489] Running loglikelihood_rolling requests
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.07it/s]
wikitext: {'alias': 'wikitext', 'word_perplexity,none': 11.75249676221893, 'word_perplexity_stderr,none': 'N/A', 'byte_perplexity,none': 1.6107673755110918, 'byte_perplexity_stderr,none': 'N/A', 'bits_per_byte,none': 0.6877481573410492, 'bits_per_byte_stderr,none': 'N/A'}
</details>

**Review by msaroufim — APPROVED** [review]

**Comment by Diogo-V** [comment]
@msaroufim - I would love to work on that! I just have one question:
I am more or less familiar with CI/CD as I have done some infra work but I am not entirely sure how to iterate and validate this on torchao's CI. If I make a commit, will the job run automatically? I remember you mentioning that workflows need to be triggered manually by someone on the team. Could you give me some pointers on how I should go about this?

Also, just a heads-up, I’ll be out of the office next week but will be back on the 25th. If the PR becomes a higher priority while I am away, feel free to move it forward as needed!

**Comment by msaroufim** [comment]
Hmm maybe I'll do some quick video tutorial on GitHub actions I've found myself explaining this stuff a lot

**Pull request merged**
