### PR TITLE
Remove int_scaled_mm's dependency on triton for cpu

### PR DESCRIPTION
**Pull request by Xia-Weiwen**
The `int_scaled_mm` op in Torchao is designed for CUDA at the beginning. However, this op is also needed for CPU. This PR adds a path for CPU in `intmm.int_scaled_mm`. It is not registered as and implementation for `torchao.int_scaled_mm` because we want to use Inductor for further optimization which cannot recognize the `torchao.int_scaled_mm` op.

This change requires this PR https://github.com/pytorch/pytorch/pull/136942. Otherwise, there might be numerical issues. So, it works with pytorch nightly since 20241026.

Test is covered by `test/kernel/test_autotuner.py` and `test/prototype/test_smoothquant.py`.

### CODE REVIEW

**Comment by Xia-Weiwen** [comment]
Hi @cpuhrsch Could you please review and see if the changes are reasonable to you? Thanks.

**Comment by Xia-Weiwen** [comment]
Hi @cpuhrsch Could you please suggest how to deal with the issue (CPU impl availability depends on triton and AUTOTUNER_ENABLE)? Thanks!

**Comment by cpuhrsch** [comment]
Hey @Xia-Weiwen - Thank you for the PR! Sorry for the delay in review. Also, please note the CI hasn't run green.

Another way to resolve this could be to move

```
@torch.library.impl(lib, "int_scaled_matmul", "CPU")
def int_scaled_matmul_cpu(a, b, scales1):
    c = torch._int_mm(a, b)
    return c.to(scales1.dtype) * scales1
```
into `torchao/kernel/intmm.py` which shouldn't have a dependency on triton. Just be sure to also define `lib = torch.library.Library("torchao", "FRAGMENT")`

**Comment by Xia-Weiwen** [comment]
@cpuhrsch Thanks! I will give it a try. A question is what `AUTOTUNER_ENABLE` is and whether CPU impl should depend on it or not.

**Comment by cpuhrsch** [comment]
@Xia-Weiwen - it's used for a Triton autotuner that allows us to cycle over a very large number of configs for a given fixed input shape. See https://github.com/pytorch-labs/ao/tree/main/torchao/kernel#autotuner-and-custom-triton-kernels

**Comment by Xia-Weiwen** [comment]
Thank you @cpuhrsch. Looks like CPU impl does not need this.

**Comment by Xia-Weiwen** [comment]
Hi @cpuhrsch This PR requires latest torch nightly (after 20241026) to pass CI. May I know when torch nightly will be updated in the CI? Thanks.

**Comment by cpuhrsch** [comment]
@Xia-Weiwen - can you try merging the latest version of main? You might be built on top of a commit that pinned the nightly version. I see `dev20241022` here: https://github.com/pytorch/ao/actions/runs/11550979799/job/32147052309?pr=128

**Comment by Xia-Weiwen** [comment]
> @Xia-Weiwen - can you try merging the latest version of main? You might be built on top of a commit that pinned the nightly version. I see `dev20241022` here: https://github.com/pytorch/ao/actions/runs/11550979799/job/32147052309?pr=128

Thanks

**Pull request merged**
