### PR TITLE
Revert "Add layout option to woq int4 api (#670)"

### PR DESCRIPTION
**Pull request by msaroufim**
This reverts commit 009f55f2acd90b8b31b3d5414a8cb4a4b47c709f.

### CODE REVIEW

**Comment by Diogo-V** [comment]
@msaroufim - Just saw that you had to revert this commit. Is there anything that I can help out on?

**Comment by msaroufim** [comment]
Thanks for checking @Diogo-V - the breakage I saw wasn't due to your PR, the breakage just happened to be observed when your PR was merged to main

So all g! But again really appreciate you checking!

**Comment by Diogo-V** [comment]
Of course! I usually follow my PRs to prod until I know that everything is fine and working :)

If there was any way that I could have spotted it, let me know and I will be sure to check it next time! As of now, the only way that I test the code is by running the command `pytest test/` which I don't know if it covers everything.

**Comment by Diogo-V** [comment]
Regarding #670, do you want me to open it again and/or make any modifications to it?

**Comment by msaroufim** [comment]
Nope no action needed!

**Pull request closed without merging**
