### PR TITLE
Move op definition for custom kernel from C++ to Python

### PR DESCRIPTION
**Pull request by gau-nernst**
## Problem

Currently op definitions for our custom kernels are defined in C++. If, for some reasons, building torchao from source does not compile these C++ files, there will be undefined ops error when importing `torchao.ops`. #929

## Solution

Move these op definitions to Python to ensure that the ops are always defined, regardless of whether the C++ files are built.

### CODE REVIEW

**Review by msaroufim — APPROVED** [review]

**Comment by elfisworking** [comment]
@gau-nernst i compile torchao 0.0.5 version by using this pr in HW device.  And i run the code following https://pytorch.org/torchtune/main/tutorials/qat_finetune.html. But the result is 
image
. can you help me ? thanks very much

**Comment by gau-nernst** [comment]
@elfisworking It looks unrelated to this PR. What is the device you are running this on? Looks like NPU, which torchao probably does not support officially. And your screenshot only shows a warning, not an error, so things should still be fine? Anyway, you should open a separate issue if something is not working as intended.

**Comment by elfisworking** [comment]
> @elfisworking It looks unrelated to this PR. What is the device you are running this on? Looks like NPU, which torchao probably does not support officially. And your screenshot only shows a warning, not an error, so things should still be fine? Anyway, you should open a separate issue if something is not working as intended.

thanks for  your reply. yes, i run torchao in npu that is a huawei aarch device. Following https://pytorch.org/torchtune/main/tutorials/qat_finetune.html,  when i run this code
>>> print(prepared_model.layers[0].attn)
MultiHeadAttention(
  (q_proj): Int8DynActInt4WeightQATLinear(in_features=4096, out_features=4096, bias=False)
  (k_proj): Int8DynActInt4WeightQATLinear(in_features=4096, out_features=1024, bias=False)
  (v_proj): Int8DynActInt4WeightQATLinear(in_features=4096, out_features=1024, bias=False)
  (output_proj): Int8DynActInt4WeightQATLinear(in_features=4096, out_features=4096, bias=False)
  (pos_embeddings): RotaryPositionalEmbeddings()
).

**Comment by gau-nernst** [comment]
@elfisworking Yes, you should raise a separate issue.

**Pull request merged**
