### PR TITLE
Issue #998 Fix

### PR DESCRIPTION
**Pull request by DevyRuxpin**
Possible solution to issue #998

### CODE REVIEW

**Comment by msaroufim** [comment]
Might need to also add some tests so CI signal is helpful and just to be clear are we only supporting bf16 moving forward or both fp16 and bf16?

**Comment by gau-nernst** [comment]
I think we shouldn't remove FP16 support, since it is the original dtype that Quant-LLM support. Not sure how we can structure it nicely (i.e. support both FP16 and BF16), but you can come up with a way first. Ideally it shouldn't have intrusive changes to the original code, so if there are upstream updates, it's easier for us to pull the new updates in. Maybe some kind of templates or just have a separate folder for BF16?

**Comment by DevyRuxpin** [comment]
I will work on this further. Thank you for feedback, i will draw things back some on the changes and incorporate your suggestions. i will work on this tonight/tomorrow.

**Comment by tobiasvanderwerff** [comment]
@gau-nernst @msaroufim I have already been working on a templated solution that supports both FP16 and BF16, and it is almost finished (see the diff [here](https://github.com/pytorch/ao/compare/main...tobiasvanderwerff:ao:fp6-bf16)). I think this would be a better solution than removing FP16 all together.

I'm just smoothing out some final bugs and it should be as good as ready. I didn't make a PR yet because I wanted to make sure that everything worked properly first. In hindsight, it might have been better to already create a PR to avoid the duplicate work done here (although I did say I was working on this feature in the original issue).

**Pull request closed without merging**
